FROM golang:1.19-buster AS build
RUN apt-get update && apt-get install musl-dev -y
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN CGO_ENABLED=0 go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /app
COPY ./ /app
RUN go mod download
RUN go build -o /fetchapp
RUN chmod +x ./dlv.sh 
ENTRYPOINT ["./dlv.sh"]


FROM gcr.io/distroless/base-debian10 AS prod
WORKDIR /
COPY --from=build /fetchapp /fetchapp
USER nonroot:nonroot
ENTRYPOINT ["/fetchapp"]