version: '3.8'
services:
  authapp:
    container_name: efishery_luthfi_authapp
    image: efishery/yufajjiru/authapp:1.0.0
    build: 
      context: ./AuthApp
      target: build
    environment:
      - port=8040
      - dlv_port=2345
    expose:
      - 2345
      - 8040
    ports:
      - 2345:2345
      - 8040:8040
    volumes:
      - ./AuthApp:/app
    security_opt:
      - "seccomp:unconfined"
  fetchapp:
    container_name: efishery_luthfi_fetchapp
    image: efishery/yufajjiru/fetchapp:1.0.0
    build: 
      context: ./FetchApp
      target: build
    environment:
      - port=8041
      - dlv_port=2346
      - authapp_url="localhost:8040"
    expose:
      - 2346
      - 8041
    ports:
      - 2346:2346
      - 8041:8041
    volumes:
      - ./FetchApp:/app
    security_opt:
      - "seccomp:unconfined"