FROM golang:1.19-buster AS build
RUN apt-get update && apt-get install musl-dev -y
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /app
COPY ./ /app
RUN go mod download
RUN go build -o /authapp
RUN chmod +x ./dlv.sh 
ENTRYPOINT [ "./dlv.sh"]


FROM gcr.io/distroless/base-debian10
WORKDIR /
COPY --from=build /authapp /authapp
USER nonroot:nonroot
ENTRYPOINT ["/authapp"]