FROM golang:1.19-buster AS build
RUN apt-get update && apt-get install musl-dev -y
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN CGO_ENABLED=0 go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /app
COPY ./ /app
RUN go mod download
RUN go build -o /authapp
RUN chmod +x ./dlv.sh
RUN chmod +w authapp.sqlite
ENTRYPOINT ["./dlv.sh"]


FROM golang:1.19-buster AS prod
WORKDIR /
COPY --from=build /authapp /authapp
COPY --from=build /app/authapp.sqlite /

ENTRYPOINT ["/authapp"]